export enum TradeProvider {
    UNI_V2 = 'uni-v2',
    UNI_V3 = 'uni-v3',
    ONE_INCH = '1inch',
    OPEN_OCEAN = 'open-ocean',
    WRAP = 'wrap',
    IZUMI = 'izumi',
    OCTOPOOL = 'octopool',
    SYMBIOSIS = 'symbiosis',
    THORCHAIN_BRIDGE = 'thorchain-bridge',
    CHAINFLIP_BRIDGE = 'chainflip-bridge',
    RAYDIUM = 'raydium',
    STONFI = 'stonfi',
    DEDUST = 'dedust',
    JUPITER = 'jupiter',
    DEPOSITORY = 'depository',
    CHANGELLY = 'changelly',
    UNI_V4 = 'uni-v4',
    KYBER_SWAP = 'kyber-swap',
    ZERO_X = '0x',
    BITGET = 'bitget',
    INTENT_SOLVER = 'intent-solver',
}

export type OneInchProtocols = string[]
